name: Build docker container Image and Push to ACR


on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main

permissions:
      id-token: write
      contents: read

# on:
#    workflow_dispatch:

# on:
#   push:
#     branches:
#       - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - name: repo Checkout
      uses: actions/checkout@v2
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/rg_acr.sh
          $GITHUB_WORKSPACE/rg_acr.sh


    - name: azure ACR login
      uses: azure/docker-login@v1
      with:
        login-server: devopsforu3013.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t devopsforu3013.azurecr.io/myapp:${{ github.sha }}
        docker push devopsforu3013.azurecr.io/myapp:${{ github.sha }}
